## Ty Johnson
## PA8
## 11 April 2023
## Version 0

In [2]:
import numpy as np

In [3]:
arr = np.array([[10,20],[30,40]])
arraySq = arr ** 2
print(arraySq)

[[ 100  400]
 [ 900 1600]]


In [4]:
arrHundred = arr + 100
print(arrHundred)

[[110 120]
 [130 140]]


In [5]:
arrFive = arr * 5
print(arrFive)

[[ 50 100]
 [150 200]]


In [6]:
arrSqrt = np.sqrt(arr)
print(arrSqrt)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [7]:
arr2 = np.arange(3,30,3).reshape(3,3)
print('\n',arr2)
arr3 = np.linspace(10,20,9).reshape(3,3)
print('\n',arr3)

print('\n',arr2 * arr3)


 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]

 [[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]

 [[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


In [14]:
one = np.load('process1.npy')
two = np.load('process2.npy')
three = np.load('process3.npy')
four = np.load('process4.npy')
five = np.load('process5.npy')

stacked = np.stack([one,two,three,four,five]).reshape(5,5)

print(stacked)

colMean = np.mean(stacked)
print(f'\nThe mean is {colMean}')

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]

The mean is 41.04
